v1.01 - Single resize + Batch resize
- Also added library exist check

diff --git a/imageResizeBatch b/imageResizeBatch
--- a/imageResizeBatch
+++ b/imageResizeBatch
@@ -1,28 +1,41 @@
 #!/bin/sh
 #
-# This is a script that uses ImageMagick to resizes images to a specified size.
+# This is a script that uses ImageMagick to resize (downsize only) all images at a directory path to a specified size.
 #
-# Accepts: png, jpg, jpeg, gif
-# Outputs: png
-# Usage: ./imgRsz.sh WIDTH HEIGHT
+# Accepts: 	png, jpg, jpeg, gif
+# Outputs: 	png
+# Usage: 	./imageResizeBatch.sh WIDTH HEIGHT directoryPath
+# Ex:		./imageResizeBatch.sh 320 480 ~
 # 
-# Tested Environment
-# OSX:			10.11.3
-# ImageMagick:	6.8.8-0 Q16 x86_64
+# Latest Test Environment
+# OSX:			10.12.3
+# ImageMagick:	7.0.5-4 Q16 x86_64
 # 
+
+
+# =====================================
+# ==========[ Library Check ]==========
+# =====================================
+
+command -v convert >/dev/null 2>&1 || { 
+	echo >&2 'Error: cannot find "convert" command.... Is ImageMagick installed?'; 
+	exit 1; 
+}
 
 # ================================================
 # ==========[ Arguments Validity Check ]==========
 # ================================================
 
-if [ "$#" -ne 2 ]; then
-	echo "Error: Incorrect number of arguments"
-	echo "Usage: ./imgRsz.sh WIDTH HEIGHT"
+if [ "$#" -ne 3 ]; then
+	echo "Error:   Incorrect number of arguments"
+	echo "Usage:   imageResizeBatch.sh WIDTH HEIGHT dirPath"
+	echo "Example: imageResizeBatch 360 480 ~"
 	exit 1
 fi
 
 width=$1
 height=$2
+dirPath=$3
 
 numRegExp='^[0-9]+$'
 if ! [[ $width =~ $numRegExp ]] ; then
@@ -31,6 +44,10 @@ if ! [[ $width =~ $numRegExp ]] ; then
 fi
 if ! [[ $height =~ $numRegExp ]] ; then
    echo "Error: Height is not a valid number" >&2
+   exit 1
+fi
+if [ ! -d "$dirPath" ]; then
+   echo "Error: Directory path does not exist ($dirPath)" >&2
    exit 1
 fi
 
@@ -47,7 +64,6 @@ do
     fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif"`
 	fileName="${fileFullName%.*}"
 	fileExt="${fileFullName##*.}"
-	
 	if [ -n "$fileFullName" ] ; then
     	let "numConversions += 1"
     fi
@@ -60,29 +76,14 @@ done
 curConversion=0
 for f in *
 do
-    fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif"`
+	let "curConversion += 1"
+	echo "[""$curConversion"" / "" $numConversions""]"
 
+    fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif"`
 	fileName="${fileFullName%.*}"
 	fileExt="${fileFullName##*.}"
-
 	if [ -n "$fileFullName" ] ; then
-		let "curConversion += 1"
-		printf "[""$curConversion"" / "" $numConversions""]"" "$fileFullName" ......"
-
-		# 1/3 - Strip(reconvert) non-standard PNG (Left by amazing Photoshop.)
-		if [ $fileExt == "png" ] ; then
-			convert "$fileFullName" -strip "$fileFullName"
-		fi
-		
-		# 2/3 - The actual conversion
-		convert "$fileName"".""$fileExt" -resize "$width""x""$height"\> "$fileName"".png"
-		
-		# 3/3 - Cleanup - Original PNGs are overwritten. Remove anything not originally PNG format
-		if [ $fileExt != "png" ] ; then
-			rm $fileFullName
-		fi
-
-		echo " Done!"		
+    	let "numConversions += 1"
     fi
 done
 
